# This is a basic workflow to help you get started with Actions

name: 'open chrome do something'

# Controls when the workflow will run
on:
  push
  # Triggers the workflow
  #schedule:
   # - cron: '* 2 * * *'
     
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'wb sign'
        run: bash ./wb.sh
      
