on: push
 

jobs:
  bot:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 132
          install-chromedriver: true
      - uses: actions/setup-python@v5
        with:
           python-version: 3.8
           cache: 'pip'
      - run: |
          pip install -r ./sino/requirements.txt
