on: push
 

jobs:
  bot:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 132
          install-chromedriver: true
